repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-xml
      - id: check-json
      - id: check-yaml
        exclude: meta.yaml
        args: [--allow-multiple-documents, --unsafe]
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.20.0"
    hooks:
    - id: pyupgrade
      args: [--py38-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        additional_dependencies:
          - toml
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
    - id: python-check-blanket-noqa
    - id: python-no-log-warn
    - id: python-use-type-annotations
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
    - id: docformatter
